using System;
using System.Collections.Generic;
using NavisworksIfcExporter.Model;
using ComApi = Autodesk.Navisworks.Api.Interop.ComApi;

namespace NavisworksIfcExporter.Geometry
{
    /// <summary>
    /// Receives geometry primitives generated by Navisworks for a fragment and
    /// accumulates them into a de-duplicated triangle mesh in WORLD coordinates.
    ///
    /// Navisworks calls back per primitive (triangle / line / point). We only
    /// keep triangles. Each fragment supplies its own local-to-world matrix, set
    /// via <see cref="SetMatrix"/> before that fragment's primitives are generated.
    ///
    /// The COM arrays returned here are VARIANT arrays whose lower bound is not
    /// guaranteed to be 0, so we always read via GetLowerBound.
    /// </summary>
    public class CallbackGeomListener : ComApi.InwSimplePrimitivesCB
    {
        // Column-major 4x4 transform for the current fragment.
        private readonly double[] _m = Identity();

        private readonly List<double> _coords = new List<double>();
        private readonly List<int> _indices = new List<int>();

        // Vertex de-duplication. Rounded key avoids float noise blowing up the table.
        private readonly Dictionary<long, int> _vertexLookup = new Dictionary<long, int>();
        private readonly List<(double x, double y, double z)> _vertices = new List<(double, double, double)>();

        // First per-vertex colour seen (RGBA 0..1), used as the element colour.
        private double[] _color;

        /// <summary>Set the local-to-world matrix for the fragment about to be generated.</summary>
        /// <param name="localToWorldMatrix">The object returned by InwOaFragment3.GetLocalToWorldMatrix().</param>
        public void SetMatrix(object localToWorldMatrix)
        {
            var transform = (ComApi.InwLTransform3f3)localToWorldMatrix;
            Array matrix = (Array)(object)transform.Matrix;
            int lb = matrix.GetLowerBound(0);
            for (int i = 0; i < 16; i++)
                _m[i] = Convert.ToDouble(matrix.GetValue(lb + i));
        }

        public void Triangle(ComApi.InwSimpleVertex v1, ComApi.InwSimpleVertex v2, ComApi.InwSimpleVertex v3)
        {
            CaptureColor(v1);
            _indices.Add(AddVertex(v1));
            _indices.Add(AddVertex(v2));
            _indices.Add(AddVertex(v3));
        }

        // We do not export edges or points to IFC, but the interface requires them.
        public void Line(ComApi.InwSimpleVertex v1, ComApi.InwSimpleVertex v2) { }
        public void Point(ComApi.InwSimpleVertex v1) { }
        public void SnapPoint(ComApi.InwSimpleVertex v1) { }

        /// <summary>Build the accumulated data into a MeshGeometry (or null if empty).</summary>
        public MeshGeometry ToMesh()
        {
            if (_indices.Count == 0)
                return null;

            var mesh = new MeshGeometry();
            mesh.Coordinates.AddRange(_coords);
            mesh.TriangleIndices.AddRange(_indices);
            mesh.Color = _color;
            return mesh;
        }

        // Reads the colour from a vertex (only present when eCOLOR was requested).
        // The colour is a VARIANT float array (RGB or RGBA, 0..1).
        private void CaptureColor(ComApi.InwSimpleVertex v)
        {
            if (_color != null)
                return;
            try
            {
                Array a = (Array)(object)v.color;
                if (a == null || a.Length < 3)
                    return;
                int lb = a.GetLowerBound(0);
                double r = Convert.ToDouble(a.GetValue(lb));
                double g = Convert.ToDouble(a.GetValue(lb + 1));
                double b = Convert.ToDouble(a.GetValue(lb + 2));
                double alpha = a.Length >= 4 ? Convert.ToDouble(a.GetValue(lb + 3)) : 1.0;
                _color = new[] { r, g, b, alpha };
            }
            catch
            {
                // Colour not available for this geometry; leave as null.
            }
        }

        private int AddVertex(ComApi.InwSimpleVertex v)
        {
            Array a = (Array)(object)v.coord;
            int lb = a.GetLowerBound(0);
            double lx = Convert.ToDouble(a.GetValue(lb));
            double ly = Convert.ToDouble(a.GetValue(lb + 1));
            double lz = Convert.ToDouble(a.GetValue(lb + 2));

            // Column-major transform: world = M * local
            double wx = _m[0] * lx + _m[4] * ly + _m[8] * lz + _m[12];
            double wy = _m[1] * lx + _m[5] * ly + _m[9] * lz + _m[13];
            double wz = _m[2] * lx + _m[6] * ly + _m[10] * lz + _m[14];

            long key = VertexKey(wx, wy, wz);
            if (_vertexLookup.TryGetValue(key, out int existing))
                return existing;

            int index = _vertices.Count;
            _vertices.Add((wx, wy, wz));
            _vertexLookup[key] = index;
            _coords.Add(wx);
            _coords.Add(wy);
            _coords.Add(wz);
            return index;
        }

        // Quantise to ~0.1mm grid (model units assumed ~mm/m scale) for de-dup hashing.
        private static long VertexKey(double x, double y, double z)
        {
            unchecked
            {
                long kx = (long)Math.Round(x * 10000.0);
                long ky = (long)Math.Round(y * 10000.0);
                long kz = (long)Math.Round(z * 10000.0);
                long hash = 17;
                hash = hash * 31 + kx;
                hash = hash * 31 + ky;
                hash = hash * 31 + kz;
                return hash;
            }
        }

        private static double[] Identity()
        {
            return new double[]
            {
                1, 0, 0, 0,
                0, 1, 0, 0,
                0, 0, 1, 0,
                0, 0, 0, 1
            };
        }
    }
}
